# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import basic_pb2

DESCRIPTOR = descriptor.FileDescriptor(
  name='message.proto',
  package='',
  serialized_pb='\n\rmessage.proto\x1a\x0b\x62\x61sic.proto\"\xc5\x01\n\tPBMessage\x12\x12\n\nmessage_id\x18\x01 \x02(\t\x12\x10\n\x08\x66rom_uid\x18\x02 \x02(\t\x12\x0e\n\x06to_uid\x18\x03 \x02(\t\x12\x1c\n\x04type\x18\x04 \x02(\x0e\x32\x0e.PBMessageType\x12 \n\x06status\x18\x05 \x02(\x0e\x32\x10.PBMessageStatus\x12\x0e\n\x06\x63_date\x18\x06 \x02(\x05\x12\x0c\n\x04text\x18\n \x01(\t\x12\x11\n\timage_url\x18\x0b \x01(\t\x12\x11\n\tsound_url\x18\x0c \x01(\t*/\n\rPBMessageType\x12\x08\n\x04TEXT\x10\x01\x12\t\n\x05IMAGE\x10\x02\x12\t\n\x05SOUND\x10\x03*>\n\x0fPBMessageStatus\x12\n\n\x06UNREAD\x10\x01\x12\x08\n\x04READ\x10\x02\x12\x0b\n\x07SENDING\x10\x03\x12\x08\n\x04SENT\x10\x04')

_PBMESSAGETYPE = descriptor.EnumDescriptor(
  name='PBMessageType',
  full_name='PBMessageType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    descriptor.EnumValueDescriptor(
      name='TEXT', index=0, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='IMAGE', index=1, number=2,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='SOUND', index=2, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=230,
  serialized_end=277,
)


_PBMESSAGESTATUS = descriptor.EnumDescriptor(
  name='PBMessageStatus',
  full_name='PBMessageStatus',
  filename=None,
  file=DESCRIPTOR,
  values=[
    descriptor.EnumValueDescriptor(
      name='UNREAD', index=0, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='READ', index=1, number=2,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='SENDING', index=2, number=3,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='SENT', index=3, number=4,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=279,
  serialized_end=341,
)


TEXT = 1
IMAGE = 2
SOUND = 3
UNREAD = 1
READ = 2
SENDING = 3
SENT = 4



_PBMESSAGE = descriptor.Descriptor(
  name='PBMessage',
  full_name='PBMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='message_id', full_name='PBMessage.message_id', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='from_uid', full_name='PBMessage.from_uid', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='to_uid', full_name='PBMessage.to_uid', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='type', full_name='PBMessage.type', index=3,
      number=4, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='status', full_name='PBMessage.status', index=4,
      number=5, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='c_date', full_name='PBMessage.c_date', index=5,
      number=6, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='text', full_name='PBMessage.text', index=6,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='image_url', full_name='PBMessage.image_url', index=7,
      number=11, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='sound_url', full_name='PBMessage.sound_url', index=8,
      number=12, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=31,
  serialized_end=228,
)

_PBMESSAGE.fields_by_name['type'].enum_type = _PBMESSAGETYPE
_PBMESSAGE.fields_by_name['status'].enum_type = _PBMESSAGESTATUS
DESCRIPTOR.message_types_by_name['PBMessage'] = _PBMESSAGE

class PBMessage(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PBMESSAGE
  
  # @@protoc_insertion_point(class_scope:PBMessage)

# @@protoc_insertion_point(module_scope)
