# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import service
from google.protobuf import service_reflection
from google.protobuf import descriptor_pb2
_PBMESSAGETYPE = descriptor.EnumDescriptor(
  name='PBMessageType',
  full_name='PBMessageType',
  filename='PBMessageType',
  values=[
    descriptor.EnumValueDescriptor(
      name='TEXT', index=0, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='IMAGE', index=1, number=2,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='SOUND', index=2, number=3,
      options=None,
      type=None),
  ],
  options=None,
)


_PBMESSAGESTATUS = descriptor.EnumDescriptor(
  name='PBMessageStatus',
  full_name='PBMessageStatus',
  filename='PBMessageStatus',
  values=[
    descriptor.EnumValueDescriptor(
      name='UNREAD', index=0, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='READ', index=1, number=2,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='SENDING', index=2, number=3,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='SENT', index=3, number=4,
      options=None,
      type=None),
  ],
  options=None,
)


TEXT = 1
IMAGE = 2
SOUND = 3
UNREAD = 1
READ = 2
SENDING = 3
SENT = 4



_PBMESSAGE = descriptor.Descriptor(
  name='PBMessage',
  full_name='PBMessage',
  filename='message.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='message_id', full_name='PBMessage.message_id', index=0,
      number=1, type=9, cpp_type=9, label=2,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='from_uid', full_name='PBMessage.from_uid', index=1,
      number=2, type=9, cpp_type=9, label=2,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='to_uid', full_name='PBMessage.to_uid', index=2,
      number=3, type=9, cpp_type=9, label=2,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='type', full_name='PBMessage.type', index=3,
      number=4, type=14, cpp_type=8, label=2,
      default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='status', full_name='PBMessage.status', index=4,
      number=5, type=14, cpp_type=8, label=2,
      default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='text', full_name='PBMessage.text', index=5,
      number=10, type=9, cpp_type=9, label=1,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='image_url', full_name='PBMessage.image_url', index=6,
      number=11, type=9, cpp_type=9, label=1,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='sound_url', full_name='PBMessage.sound_url', index=7,
      number=12, type=9, cpp_type=9, label=1,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)

import basic_pb2

_PBMESSAGE.fields_by_name['type'].enum_type = _PBMESSAGETYPE
_PBMESSAGE.fields_by_name['status'].enum_type = _PBMESSAGESTATUS

class PBMessage(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PBMESSAGE

