# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import service
from google.protobuf import service_reflection
from google.protobuf import descriptor_pb2
_PBRESULTCODE = descriptor.EnumDescriptor(
  name='PBResultCode',
  full_name='PBResultCode',
  filename='PBResultCode',
  values=[
    descriptor.EnumValueDescriptor(
      name='SUCCESS', index=0, number=0,
      options=None,
      type=None),
  ],
  options=None,
)


SUCCESS = 0



_PBRESPONSE = descriptor.Descriptor(
  name='PBResponse',
  full_name='PBResponse',
  filename='response.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='code', full_name='PBResponse.code', index=0,
      number=1, type=14, cpp_type=8, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='error_message', full_name='PBResponse.error_message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='actions', full_name='PBResponse.actions', index=2,
      number=10, type=11, cpp_type=10, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='messages', full_name='PBResponse.messages', index=3,
      number=11, type=11, cpp_type=10, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='users', full_name='PBResponse.users', index=4,
      number=12, type=11, cpp_type=10, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='activitys', full_name='PBResponse.activitys', index=5,
      number=13, type=11, cpp_type=10, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='comments', full_name='PBResponse.comments', index=6,
      number=14, type=11, cpp_type=10, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='user', full_name='PBResponse.user', index=7,
      number=50, type=11, cpp_type=10, label=1,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='action', full_name='PBResponse.action', index=8,
      number=51, type=11, cpp_type=10, label=1,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='merchant', full_name='PBResponse.merchant', index=9,
      number=52, type=11, cpp_type=10, label=1,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)

import basic_pb2
import user_pb2
import action_pb2
import message_pb2

_PBRESPONSE.fields_by_name['code'].enum_type = _PBRESULTCODE
_PBRESPONSE.fields_by_name['actions'].message_type = action_pb2._PBACTION
_PBRESPONSE.fields_by_name['messages'].message_type = message_pb2._PBMESSAGE
_PBRESPONSE.fields_by_name['users'].message_type = user_pb2._PBUSERBASIC
_PBRESPONSE.fields_by_name['activitys'].message_type = action_pb2._PBACTIVITY
_PBRESPONSE.fields_by_name['comments'].message_type = action_pb2._PBCOMMENT
_PBRESPONSE.fields_by_name['user'].message_type = user_pb2._PBUSER
_PBRESPONSE.fields_by_name['action'].message_type = action_pb2._PBACTION
_PBRESPONSE.fields_by_name['merchant'].message_type = action_pb2._PBMERCHANT

class PBResponse(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PBRESPONSE

