# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import service
from google.protobuf import service_reflection
from google.protobuf import descriptor_pb2
_PBRELATION = descriptor.EnumDescriptor(
  name='PBRelation',
  full_name='PBRelation',
  filename='PBRelation',
  values=[
    descriptor.EnumValueDescriptor(
      name='FOLLOW', index=0, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='FAN', index=1, number=2,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='FRIEND', index=2, number=3,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='BLACK', index=3, number=4,
      options=None,
      type=None),
  ],
  options=None,
)


_PBREGTYPE = descriptor.EnumDescriptor(
  name='PBRegType',
  full_name='PBRegType',
  filename='PBRegType',
  values=[
    descriptor.EnumValueDescriptor(
      name='NICK', index=0, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='QQ', index=1, number=3,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='RENREN', index=2, number=4,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='EMAIL', index=3, number=5,
      options=None,
      type=None),
  ],
  options=None,
)


_PBUSERROLE = descriptor.EnumDescriptor(
  name='PBUserRole',
  full_name='PBUserRole',
  filename='PBUserRole',
  values=[
    descriptor.EnumValueDescriptor(
      name='USER', index=0, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='AMDIN', index=1, number=2,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='VIP', index=2, number=3,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='FORBIDDEN', index=3, number=4,
      options=None,
      type=None),
  ],
  options=None,
)


_PBUSERSTATUS = descriptor.EnumDescriptor(
  name='PBUserStatus',
  full_name='PBUserStatus',
  filename='PBUserStatus',
  values=[
    descriptor.EnumValueDescriptor(
      name='OFFLINE', index=0, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='ONLINE', index=1, number=2,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='HIDDEN', index=2, number=3,
      options=None,
      type=None),
  ],
  options=None,
)


FOLLOW = 1
FAN = 2
FRIEND = 3
BLACK = 4
NICK = 1
QQ = 3
RENREN = 4
EMAIL = 5
USER = 1
AMDIN = 2
VIP = 3
FORBIDDEN = 4
OFFLINE = 1
ONLINE = 2
HIDDEN = 3



_PBSNS = descriptor.Descriptor(
  name='PBSNS',
  full_name='PBSNS',
  filename='user.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='tel_number', full_name='PBSNS.tel_number', index=0,
      number=1, type=9, cpp_type=9, label=1,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='qq_number', full_name='PBSNS.qq_number', index=1,
      number=2, type=9, cpp_type=9, label=1,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='qq_weibo_id', full_name='PBSNS.qq_weibo_id', index=2,
      number=3, type=9, cpp_type=9, label=1,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='qq_weibo_nick', full_name='PBSNS.qq_weibo_nick', index=3,
      number=4, type=9, cpp_type=9, label=1,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='sina_weibo_id', full_name='PBSNS.sina_weibo_id', index=4,
      number=5, type=9, cpp_type=9, label=1,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='sina_weibo_nick', full_name='PBSNS.sina_weibo_nick', index=5,
      number=6, type=9, cpp_type=9, label=1,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='renren_id', full_name='PBSNS.renren_id', index=6,
      number=7, type=9, cpp_type=9, label=1,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='renren_nick', full_name='PBSNS.renren_nick', index=7,
      number=8, type=9, cpp_type=9, label=1,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_PBLOG = descriptor.Descriptor(
  name='PBLog',
  full_name='PBLog',
  filename='user.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='last_log_date', full_name='PBLog.last_log_date', index=0,
      number=1, type=5, cpp_type=1, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='last_log_ip', full_name='PBLog.last_log_ip', index=1,
      number=2, type=5, cpp_type=1, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='last_log_latitude', full_name='PBLog.last_log_latitude', index=2,
      number=3, type=2, cpp_type=6, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='last_log_longitude', full_name='PBLog.last_log_longitude', index=3,
      number=4, type=2, cpp_type=6, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_PBREGISTION = descriptor.Descriptor(
  name='PBRegistion',
  full_name='PBRegistion',
  filename='user.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='reg_date', full_name='PBRegistion.reg_date', index=0,
      number=1, type=5, cpp_type=1, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='reg_type', full_name='PBRegistion.reg_type', index=1,
      number=2, type=14, cpp_type=8, label=1,
      default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='reg_ip', full_name='PBRegistion.reg_ip', index=2,
      number=3, type=5, cpp_type=1, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_PBDEVICE = descriptor.Descriptor(
  name='PBDevice',
  full_name='PBDevice',
  filename='user.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='device_id', full_name='PBDevice.device_id', index=0,
      number=1, type=9, cpp_type=9, label=2,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='device_os', full_name='PBDevice.device_os', index=1,
      number=2, type=9, cpp_type=9, label=2,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='device_token', full_name='PBDevice.device_token', index=2,
      number=3, type=9, cpp_type=9, label=1,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='device_name', full_name='PBDevice.device_name', index=3,
      number=4, type=9, cpp_type=9, label=1,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_PBSTATISTIC = descriptor.Descriptor(
  name='PBStatistic',
  full_name='PBStatistic',
  filename='user.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='fan_count', full_name='PBStatistic.fan_count', index=0,
      number=1, type=5, cpp_type=1, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='follow_count', full_name='PBStatistic.follow_count', index=1,
      number=2, type=5, cpp_type=1, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='my_activity', full_name='PBStatistic.my_activity', index=2,
      number=3, type=5, cpp_type=1, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='new_fan_count', full_name='PBStatistic.new_fan_count', index=3,
      number=20, type=5, cpp_type=1, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='new_follow_count', full_name='PBStatistic.new_follow_count', index=4,
      number=22, type=5, cpp_type=1, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='new_message_count', full_name='PBStatistic.new_message_count', index=5,
      number=23, type=5, cpp_type=1, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='new_feed_count', full_name='PBStatistic.new_feed_count', index=6,
      number=24, type=5, cpp_type=1, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='new_notice_count', full_name='PBStatistic.new_notice_count', index=7,
      number=25, type=5, cpp_type=1, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_PBUSERBASIC = descriptor.Descriptor(
  name='PBUserBasic',
  full_name='PBUserBasic',
  filename='user.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='uid', full_name='PBUserBasic.uid', index=0,
      number=1, type=9, cpp_type=9, label=2,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='uname', full_name='PBUserBasic.uname', index=1,
      number=2, type=9, cpp_type=9, label=2,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='nick', full_name='PBUserBasic.nick', index=2,
      number=3, type=9, cpp_type=9, label=1,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='role', full_name='PBUserBasic.role', index=3,
      number=4, type=14, cpp_type=8, label=1,
      default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='gender', full_name='PBUserBasic.gender', index=4,
      number=5, type=8, cpp_type=7, label=1,
      default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='avatar', full_name='PBUserBasic.avatar', index=5,
      number=6, type=9, cpp_type=9, label=1,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='status', full_name='PBUserBasic.status', index=6,
      number=7, type=14, cpp_type=8, label=1,
      default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='introduction', full_name='PBUserBasic.introduction', index=7,
      number=8, type=9, cpp_type=9, label=1,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='birth_date', full_name='PBUserBasic.birth_date', index=8,
      number=9, type=5, cpp_type=1, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='tags', full_name='PBUserBasic.tags', index=9,
      number=10, type=9, cpp_type=9, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='password', full_name='PBUserBasic.password', index=10,
      number=11, type=9, cpp_type=9, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='PBRelation', full_name='PBUserBasic.PBRelation', index=11,
      number=20, type=5, cpp_type=1, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='note_name', full_name='PBUserBasic.note_name', index=12,
      number=21, type=9, cpp_type=9, label=1,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_PBUSER = descriptor.Descriptor(
  name='PBUser',
  full_name='PBUser',
  filename='user.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='basic_info', full_name='PBUser.basic_info', index=0,
      number=1, type=11, cpp_type=10, label=2,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='registion', full_name='PBUser.registion', index=1,
      number=2, type=11, cpp_type=10, label=1,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='log_info', full_name='PBUser.log_info', index=2,
      number=3, type=11, cpp_type=10, label=1,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='device_info', full_name='PBUser.device_info', index=3,
      number=4, type=11, cpp_type=10, label=1,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='sns_info', full_name='PBUser.sns_info', index=4,
      number=5, type=11, cpp_type=10, label=1,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='statistic', full_name='PBUser.statistic', index=5,
      number=6, type=11, cpp_type=10, label=1,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)

import basic_pb2

_PBREGISTION.fields_by_name['reg_type'].enum_type = _PBREGTYPE
_PBUSERBASIC.fields_by_name['role'].enum_type = _PBUSERROLE
_PBUSERBASIC.fields_by_name['status'].enum_type = _PBUSERSTATUS
_PBUSER.fields_by_name['basic_info'].message_type = _PBUSERBASIC
_PBUSER.fields_by_name['registion'].message_type = _PBREGISTION
_PBUSER.fields_by_name['log_info'].message_type = _PBLOG
_PBUSER.fields_by_name['device_info'].message_type = _PBDEVICE
_PBUSER.fields_by_name['sns_info'].message_type = _PBSNS
_PBUSER.fields_by_name['statistic'].message_type = _PBSTATISTIC

class PBSNS(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PBSNS

class PBLog(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PBLOG

class PBRegistion(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PBREGISTION

class PBDevice(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PBDEVICE

class PBStatistic(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PBSTATISTIC

class PBUserBasic(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PBUSERBASIC

class PBUser(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PBUSER

