# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import basic_pb2

DESCRIPTOR = descriptor.FileDescriptor(
  name='action.proto',
  package='',
  serialized_pb='\n\x0c\x61\x63tion.proto\x1a\x0b\x62\x61sic.proto\"H\n\x05\x41lbum\x12\x10\n\x08\x61lbum_id\x18\x01 \x02(\t\x12\x0b\n\x03uid\x18\x02 \x02(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x12\n\nimage_list\x18\x04 \x03(\t\"\x82\x02\n\nPBActivity\x12\x1d\n\x04type\x18\x01 \x02(\x0e\x32\x0f.PBActivityType\x12\x0e\n\x06\x63_date\x18\x02 \x02(\x05\x12\x1d\n\x08location\x18\x03 \x01(\x0b\x32\x0b.PBLocation\x12\x1b\n\x07\x63ontact\x18\x04 \x01(\x0b\x32\n.PBContact\x12\x15\n\rjoin_timeline\x18\x05 \x01(\x05\x12\x11\n\thold_time\x18\x06 \x01(\x05\x12\x15\n\rcomment_count\x18\x14 \x01(\x05\x12\x13\n\x0bshare_count\x18\x15 \x01(\x05\x12\x18\n\x10interested_count\x18\x16 \x01(\x05\x12\x19\n\x11participant_count\x18\x17 \x01(\x05*6\n\x0ePBActivityType\x12\t\n\x05PARTY\x10\x01\x12\x0b\n\x07TRAFFIC\x10\x02\x12\x0c\n\x08SHOPPING\x10\x03')

_PBACTIVITYTYPE = descriptor.EnumDescriptor(
  name='PBActivityType',
  full_name='PBActivityType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    descriptor.EnumValueDescriptor(
      name='PARTY', index=0, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='TRAFFIC', index=1, number=2,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='SHOPPING', index=2, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=364,
  serialized_end=418,
)


PARTY = 1
TRAFFIC = 2
SHOPPING = 3



_ALBUM = descriptor.Descriptor(
  name='Album',
  full_name='Album',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='album_id', full_name='Album.album_id', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='uid', full_name='Album.uid', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='name', full_name='Album.name', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='image_list', full_name='Album.image_list', index=3,
      number=4, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=29,
  serialized_end=101,
)


_PBACTIVITY = descriptor.Descriptor(
  name='PBActivity',
  full_name='PBActivity',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='type', full_name='PBActivity.type', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='c_date', full_name='PBActivity.c_date', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='location', full_name='PBActivity.location', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='contact', full_name='PBActivity.contact', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='join_timeline', full_name='PBActivity.join_timeline', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='hold_time', full_name='PBActivity.hold_time', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='comment_count', full_name='PBActivity.comment_count', index=6,
      number=20, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='share_count', full_name='PBActivity.share_count', index=7,
      number=21, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='interested_count', full_name='PBActivity.interested_count', index=8,
      number=22, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='participant_count', full_name='PBActivity.participant_count', index=9,
      number=23, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=104,
  serialized_end=362,
)

_PBACTIVITY.fields_by_name['type'].enum_type = _PBACTIVITYTYPE
_PBACTIVITY.fields_by_name['location'].message_type = basic_pb2._PBLOCATION
_PBACTIVITY.fields_by_name['contact'].message_type = basic_pb2._PBCONTACT
DESCRIPTOR.message_types_by_name['Album'] = _ALBUM
DESCRIPTOR.message_types_by_name['PBActivity'] = _PBACTIVITY

class Album(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ALBUM
  
  # @@protoc_insertion_point(class_scope:Album)

class PBActivity(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PBACTIVITY
  
  # @@protoc_insertion_point(class_scope:PBActivity)

# @@protoc_insertion_point(module_scope)
